name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: SOC=mt7981 BOARD=360t7 MULTI_LAYOUT=1 ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: output/mt7981_360t7-fip-fixed-parts.bin
